import { useState } from "react";

export default function CreateNotes() {
  const [inputType, setInputType] = useState("topic");
  const [title, setTitle] = useState("");
  const [input, setInput] = useState("");
  const [generatedNotes, setGeneratedNotes] = useState(null);

  const tabs = [
    {
      id: "topic",
      label: "Topic",
      icon: "⌕",
      placeholder: "e.g. Photosynthesis, Logistic Regression, React Hooks...",
    },
    {
      id: "content",
      label: "Paste Content",
      icon: "▤",
      placeholder: "Paste your class notes, paragraph, or study material here...",
    },
    {
      id: "video",
      label: "Video Link",
      icon: "⌁",
      placeholder: "Paste a YouTube video link here...",
    },
  ];

  const currentTab = tabs.find((tab) => tab.id === inputType);

  function handleGenerateNotes() {
    const noteTitle = title || input || "Untitled Notes";

    setGeneratedNotes({
      title: noteTitle,
      summary:
        "This is a mock AI-generated note. Later, this area will show real notes generated by your AI/LLM.",
      points: [
        "The topic is broken into simple and readable sections.",
        "Important ideas are highlighted for quick revision.",
        "The final note should help students understand faster.",
      ],
      revisionLine:
        "Revision line: Read the summary first, then revise the key points.",
    });
  }

  function handleClear() {
    setTitle("");
    setInput("");
    setGeneratedNotes(null);
  }

  return (
    <div>
      <div className="mb-6 flex items-center gap-4">
        <div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#eeeaff] text-2xl text-[#6757ff] shadow-md shadow-purple-100">
          ▤
        </div>

        <div>
          <h1 className="text-4xl font-black tracking-[-0.05em] text-[#15132b]">
            Create Notes
          </h1>
          <p className="mt-1 font-semibold text-[#9a93b3]">
            Turn your topic or content into clean study notes.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-[0.95fr_1.05fr]">
        <section className="rounded-[32px] border border-purple-100 bg-white/85 p-6 shadow-xl shadow-purple-100/60">
          <h2 className="mb-5 text-lg font-black text-[#15132b]">
            What would you like notes on?
          </h2>

          <div className="mb-5 grid grid-cols-3 rounded-2xl bg-[#f3eee8] p-1">
            {tabs.map((tab) => (
              <button
                key={tab.id}
                onClick={() => setInputType(tab.id)}
                className={`rounded-xl px-3 py-3 text-xs font-black transition ${
                  inputType === tab.id
                    ? "bg-white text-[#6757ff] shadow-md"
                    : "text-[#9a93b3] hover:text-[#15132b]"
                }`}
              >
                <span className="mr-1">{tab.icon}</span>
                {tab.label}
              </button>
            ))}
          </div>

          <textarea
            value={input}
            onChange={(event) => setInput(event.target.value)}
            placeholder={currentTab.placeholder}
            className="min-h-[190px] w-full resize-none rounded-3xl border border-transparent bg-[#f3eee8] px-5 py-4 font-semibold leading-7 text-[#15132b] outline-none transition placeholder:text-[#b7adc4] focus:border-[#6757ff] focus:bg-white"
          />

          <label className="mt-5 block text-sm font-black text-[#8a83a5]">
            Custom title optional
          </label>

          <input
            value={title}
            onChange={(event) => setTitle(event.target.value)}
            placeholder="Leave blank to auto-generate from your input"
            className="mt-2 w-full rounded-2xl border border-transparent bg-[#f3eee8] px-5 py-4 font-semibold text-[#15132b] outline-none transition placeholder:text-[#b7adc4] focus:border-[#6757ff] focus:bg-white"
          />

          <div className="mt-5 flex gap-3">
            <button
              onClick={handleGenerateNotes}
              disabled={!input.trim()}
              className="flex-1 rounded-2xl bg-gradient-to-r from-[#6757ff] to-[#b75cff] px-5 py-4 font-black text-white shadow-lg shadow-purple-200 transition hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-50"
            >
              ✨ Generate Notes
            </button>

            <button
              onClick={handleClear}
              className="rounded-2xl border border-purple-100 bg-white px-5 py-4 font-black text-[#8a83a5] transition hover:bg-[#fff5ec]"
            >
              Clear
            </button>
          </div>
        </section>

        <section className="overflow-hidden rounded-[32px] border border-purple-100 bg-white/85 shadow-xl shadow-purple-100/60">
          <div className="border-b border-purple-100 px-6 py-5">
            <h2 className="text-lg font-black text-[#15132b]">
              Generated Notes
            </h2>
          </div>

          <div className="min-h-[455px] p-6">
            {!generatedNotes ? (
              <div className="flex min-h-[390px] flex-col items-center justify-center text-center">
                <div className="mb-4 grid h-16 w-16 place-items-center rounded-3xl bg-[#eeeaff] text-3xl text-[#6757ff]">
                  ▤
                </div>
                <h3 className="font-black text-[#8a83a5]">
                  Your notes will appear here
                </h3>
                <p className="mt-2 max-w-sm text-sm leading-6 text-[#b0a8c2]">
                  Enter a topic or paste content on the left, then click
                  Generate Notes.
                </p>
              </div>
            ) : (
              <div className="space-y-5">
                <div className="rounded-3xl bg-[#fffaf3] p-5">
                  <p className="mb-2 text-xs font-black uppercase tracking-[0.2em] text-[#6757ff]">
                    Study Note
                  </p>
                  <h3 className="text-2xl font-black text-[#15132b]">
                    {generatedNotes.title}
                  </h3>
                </div>

                <div>
                  <h4 className="mb-2 font-black text-[#15132b]">Summary</h4>
                  <p className="leading-7 text-[#77718f]">
                    {generatedNotes.summary}
                  </p>
                </div>

                <div>
                  <h4 className="mb-3 font-black text-[#15132b]">
                    Key Points
                  </h4>

                  <ul className="space-y-3">
                    {generatedNotes.points.map((point) => (
                      <li
                        key={point}
                        className="rounded-2xl bg-[#f7f2ff] px-4 py-3 text-sm font-semibold leading-6 text-[#655d80]"
                      >
                        {point}
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="rounded-3xl border border-emerald-100 bg-[#edfff6] p-5">
                  <p className="font-bold leading-7 text-emerald-700">
                    {generatedNotes.revisionLine}
                  </p>
                </div>
              </div>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}